Nurse/Models/StaffViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Nurse.Models
{
    public class StaffViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string position { get; set; }
    }
}

Nurse/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nurse.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Nurse/Controllers/NurseController.cs
using Dapper;
using Nurse.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nurse.Controllers
{
    public class NurseController : Controller
    {
        // GET: Nurse
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Staff()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Staff(string id = "")
        {

            StaffViewModel model = new StaffViewModel();
            if (!string.IsNullOrEmpty(id))
            {
                int st_id = Convert.ToInt32(id);
                try
                {
                    using (NurseEntities context = new NurseEntities())
                    {
                        var st = (from s in context.staff
                                  where s.id == st_id
                                  select new StaffViewModel
                                  {
                                      id = s.id,
                                      name = s.name,
                                      surname = s.surname,
                                      position = s.position
                                  }).ToList();
                        if (st != null)
                        {
                            foreach (var item in st)
                            {
                                model.id = item.id;
                                model.name = item.name;
                                model.surname = item.surname;
                                model.position = item.position;
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(model);
        }

        public ActionResult SaveStaff(FormCollection form, StaffViewModel model)
        {
            try
            {
                using (NurseEntities context = new NurseEntities())
                {
                    staff st = new staff();
                    st.name = model.name;
                    st.surname = model.surname;
                    st.position = model.position;
                    context.staff.Add(st);
                    context.SaveChanges();
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View("Staff");
        }
    }
}

Nurse/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Nurse/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Nurse/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Nurse/Views/Nurse/Staff.cshtml
@model Nurse.Models.StaffViewModel
@{
    ViewBag.Title = "STAFF Management";
}

<h2>@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("SaveStaff", "Nurse", FormMethod.Post, new { @class = "form-horizontal", @name = "entryForm", @id = "entryForm" }))
{
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="col-md-3 control-label">ID :</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.id, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="col-md-3 control-label">Name :</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="col-md-3 control-label">Surname :</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.surname, new { @class = "form-control" })
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label class="col-md-3 control-label">Position :</label>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.position, new { @class = "form-control" })
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-default">Back</button>
        </div>
    </div>
</div>
}

Nurse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nurse Traning Report</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<img src="~/Content/Img/NTR_logo.png" />*@
                @Html.ActionLink("NTR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                    <li>@Html.ActionLink("STAFF", "Staff", "Nurse")</li>
                    <li>@Html.ActionLink("ABOUT", "About", "Home")</li>
                    <li>@Html.ActionLink("CONTACT", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nurse Traning Report</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>